apiVersion: v1
kind: Secret

metadata:
  name: db-secret

type: Opaque
stringData:
  # Example if you need multiple values
  # MYSQL_DATABASE: d29yZHByZXNzCg==
  # MYSQL_USER: d29yZHByZXNzCg==
  # MYSQL_PASSWORD: SXhCMzRxRXF0dERubXpR

  # This is base64 encoded -- the real password is NGiJi6A46YJTjTx
  password: admin123
  #MYSQL_DB_PASSWORD: wordpress123
